### ISSUE TITLE
Log httpd log_error to stderr

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/s2i-php#93]
From https://github.com/openshift/sti-perl/pull/73#issuecomment-191477670

Instead of sending stderr to a file, send it do stderr like we do in other images.

Code: [5.5/contrib/etc/httpdconf.sed#L7](https://github.com/openshift/sti-php/blob/f909e30ddc9c64bdeef645534569504be59f0aff/5.5/contrib/etc/httpdconf.sed#L7)

See the patch applied to Perl, it was very good, including tests.

**Comment by bparees** [comment]
very good except it broke on docker 1.8 :)  but we have a new/better patch now.
