### ISSUE TITLE
The PHP_INI_SCAN_DIR can be set to multiple directories (it breaks run script)

### ISSUE THREAD

**Issue by mfojtik** [openshift/s2i-php#97]
When trying to include custom directory within a source which include the custom .ini file, users have to set the `PHP_INI_SCAN_DIR=/opt/app-root/src/php:/etc/opt/rh/rh-php56/php.d`

This is supported by PHP and works, problem is this line in the run script: https://github.com/openshift/s2i-php/blob/master/5.6/s2i/bin/run#L22

this will explode and opcache will not be saved... however the httpd will run ;-)

**Comment by remicollet** [comment]
If pr #96 is merged,  It seems simpler and consistent to use default value to ":/opt/app-root/etc/php.d" and drop this line (and save 10-opcache.ini  there)

**Comment by remicollet** [comment]
So:

    export PHP_INI_SCAN_DIR=${PHP_INI_SCAN_DIR:-:/opt/app-root/etc/php.d}
    
    envsubst < /opt/app-root/etc/php.ini.template > $PHPRC
    envsubst < /opt/app-root/etc/php.d/10-opcache.ini.template > /opt/app-root/etc/php.d/10-opcache.ini

**Comment by mfojtik** [comment]
@remicollet I will make the fix to run script in #96
